bookingpricegiverservice:
  image: bookingpricegiverservice
  links:
  - eventstore
invoicecreatorservice:
  image: invoicecreatorservice
  links:
  - eventstore
reportgeneratorservice:
  image: reportgeneratorservice
  links:
  - eventstore
eventstore:
  image: adbrowne/eventstore
  ports:
  - "1113:1113"
  - "2113:2113"
